// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class AiConversation
{
    public Guid ConversationId { get; set; }

    public Guid UserId { get; set; }

    public Guid? EventId { get; set; }

    public Guid? TeamId { get; set; }

    public string Role { get; set; }

    public string Message { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Event Event { get; set; }

    public virtual Team Team { get; set; }

    public virtual User User { get; set; }
}