// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class AiGenerationRequest
{
    public Guid RequestId { get; set; }

    public string RequestType { get; set; }

    public string InputPayload { get; set; }

    public string Prompt { get; set; }

    public string Model { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<AiGenerationOutput> AiGenerationOutputs { get; set; } = new List<AiGenerationOutput>();
}