// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class AiGenerationOutput
{
    public Guid OutputId { get; set; }

    public Guid RequestId { get; set; }

    public string OutputText { get; set; }

    public string StructuredJson { get; set; }

    public int? TokensUsed { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual AiGenerationRequest Request { get; set; }
}