// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class AiInsight
{
    public Guid AiInsightId { get; set; }

    public Guid? EventId { get; set; }

    public Guid? TeamId { get; set; }

    public Guid? UserId { get; set; }

    public string EntityType { get; set; }

    public Guid? EntityId { get; set; }

    public string InsightType { get; set; }

    public string InputContext { get; set; }

    public string OutputResult { get; set; }

    public double? Score { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Event Event { get; set; }

    public virtual Team Team { get; set; }

    public virtual User User { get; set; }
}