// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class AssessmentQuestion
{
    public Guid QuestionId { get; set; }

    public Guid AssessmentId { get; set; }

    public string Question { get; set; }

    public string Options { get; set; }

    public string CorrectAnswer { get; set; }

    public string Explanation { get; set; }

    public bool? IsAiGenerated { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Hint { get; set; }

    public string QuestionType { get; set; }

    public string Metadata { get; set; }

    public string Hint1 { get; set; }

    public int? Marks { get; set; }

    public string EvaluationStrategy { get; set; }

    public virtual Assessment Assessment { get; set; }
}