// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Assessment
{
    public Guid AssessmentId { get; set; }

    public Guid TopicId { get; set; }

    public string Title { get; set; }

    public int? Difficulty { get; set; }

    public string Metadata { get; set; }

    public bool? IsAiGenerated { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? ModuleId { get; set; }

    public string AssessmentType { get; set; }

    public int? EstimatedDurationMinutes { get; set; }

    public string LearningObjectives { get; set; }

    public string Description { get; set; }

    public virtual ICollection<AssessmentQuestion> AssessmentQuestions { get; set; } = new List<AssessmentQuestion>();

    public virtual Module Module { get; set; }

    public virtual ICollection<UserAssessmentResult> UserAssessmentResults { get; set; } = new List<UserAssessmentResult>();
}