// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Assignment
{
    public Guid AssignmentId { get; set; }

    public Guid? WeekId { get; set; }

    public Guid? TopicId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ExpectedOutput { get; set; }

    public string RubricJson { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string AssignmentType { get; set; }

    public int? EstimatedDurationMinutes { get; set; }

    public virtual Week Week { get; set; }
}