// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class ChallengeProblem
{
    public Guid ProblemId { get; set; }

    public Guid ChallengeId { get; set; }

    public string Title { get; set; }

    public string ProblemStatement { get; set; }

    public virtual CodingChallenge Challenge { get; set; }

    public virtual ICollection<CodeSubmission> CodeSubmissions { get; set; } = new List<CodeSubmission>();

    public virtual ICollection<InterviewSession> InterviewSessions { get; set; } = new List<InterviewSession>();

    public virtual ICollection<ProblemTestCase> ProblemTestCases { get; set; } = new List<ProblemTestCase>();
}