// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class CodeSubmission
{
    public Guid SubmissionId { get; set; }

    public Guid ProblemId { get; set; }

    public Guid UserId { get; set; }

    public string Language { get; set; }

    public string SourceCode { get; set; }

    public double? Score { get; set; }

    public DateTime SubmittedOn { get; set; }

    public virtual ChallengeProblem Problem { get; set; }

    public virtual User User { get; set; }
}