// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class CodingChallenge
{
    public Guid ChallengeId { get; set; }

    public Guid EventId { get; set; }

    public string Title { get; set; }

    public string Difficulty { get; set; }

    public int? TimeLimitMinutes { get; set; }

    public virtual ICollection<ChallengeProblem> ChallengeProblems { get; set; } = new List<ChallengeProblem>();

    public virtual Event Event { get; set; }
}