// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Engagement
{
    public Guid EngagementId { get; set; }

    public Guid ItemId { get; set; }

    public Guid UserId { get; set; }

    public string CommentText { get; set; }

    public int? Points { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public string EngagementType { get; set; }

    public Guid? ParentCommentId { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Engagement> InverseParentComment { get; set; } = new List<Engagement>();

    public virtual KnowledgeItem Item { get; set; }

    public virtual Engagement ParentComment { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual User User { get; set; }
}