// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class EvaluationCriterion
{
    public Guid CriteriaId { get; set; }

    public Guid EventId { get; set; }

    public string Name { get; set; }

    public int? Weight { get; set; }

    public virtual Event Event { get; set; }
}