// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Event
{
    public Guid EventId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string EventType { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public Guid? OwnerId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateOnly? RegistrationCloseDate { get; set; }

    public DateOnly? MentorCheckpointStart { get; set; }

    public DateOnly? MentorCheckpointEnd { get; set; }

    public DateOnly? FinalSubmissionDeadline { get; set; }

    public DateOnly? IdeaPresentationStart { get; set; }

    public DateOnly? IdeaPresentationEnd { get; set; }

    public DateOnly? WinnersAnnouncementDate { get; set; }

    public string ContactEmail { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<EventJury> EventJuries { get; set; } = new List<EventJury>();

    public virtual ICollection<EventKnowledgeItem> EventKnowledgeItems { get; set; } = new List<EventKnowledgeItem>();

    public virtual ICollection<JuryChatMessage> JuryChatMessages { get; set; } = new List<JuryChatMessage>();

    public virtual ICollection<JuryFinalScore> JuryFinalScores { get; set; } = new List<JuryFinalScore>();

    public virtual ICollection<Mentor> Mentors { get; set; } = new List<Mentor>();

    public virtual User Owner { get; set; }

    public virtual ICollection<Presentation> Presentations { get; set; } = new List<Presentation>();

    public virtual ICollection<TeamFeedback> TeamFeedbacks { get; set; } = new List<TeamFeedback>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();

    public virtual User UpdatedByNavigation { get; set; }
}