// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class IdeaSubmission
{
    public Guid IdeaId { get; set; }

    public Guid EventId { get; set; }

    public Guid TeamId { get; set; }

    public string IdeaTitle { get; set; }

    public string IdeaDescription { get; set; }

    public string RepoUrl { get; set; }

    public string DemoUrl { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Event Event { get; set; }

    public virtual Team Team { get; set; }
}