// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class InterviewSession
{
    public Guid InterviewId { get; set; }

    public Guid UserId { get; set; }

    public Guid? ProblemId { get; set; }

    public string Transcript { get; set; }

    public float? CommunicationScore { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int QuestionCount { get; set; }

    public bool IsCompleted { get; set; }

    public DateTime CompletedOn { get; set; }

    public string FinalFeedback { get; set; }

    public virtual ChallengeProblem Problem { get; set; }

    public virtual User User { get; set; }
}