// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class JuryScoreDetail
{
    public Guid ScoreDetailId { get; set; }

    public Guid FinalId { get; set; }

    public string CriteriaName { get; set; }

    public int Score { get; set; }

    public string Remarks { get; set; }

    public virtual JuryFinalScore Final { get; set; }
}