// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class JuryFinalScore
{
    public Guid FinalId { get; set; }

    public Guid EventId { get; set; }

    public Guid TeamId { get; set; }

    public Guid? ApprovedBy { get; set; }

    public int? TotalScore { get; set; }

    public string Remarks { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public virtual User ApprovedByNavigation { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<JuryScoreDetail> JuryScoreDetails { get; set; } = new List<JuryScoreDetail>();

    public virtual Team Team { get; set; }
}