// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class JuryChatMessage
{
    public Guid MessageId { get; set; }

    public Guid EventId { get; set; }

    public Guid SenderJuryId { get; set; }

    public string Message { get; set; }

    public DateTime CreatedOn { get; set; }

    public Guid? ReplyToMessageId { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<JuryChatMessage> InverseReplyToMessage { get; set; } = new List<JuryChatMessage>();

    public virtual JuryChatMessage ReplyToMessage { get; set; }

    public virtual User SenderJury { get; set; }
}