// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class KnowledgeReview
{
    public Guid ReviewId { get; set; }

    public Guid? AssignmentId { get; set; }

    public Guid? ItemId { get; set; }

    public Guid? ReviewerId { get; set; }

    public DateTime? ReviewedOn { get; set; }

    public virtual KnowledgeReviewerAssignment Assignment { get; set; }

    public virtual KnowledgeItem Item { get; set; }

    public virtual User Reviewer { get; set; }
}