// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class LearningPlan
{
    public Guid PlanId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? DurationWeeks { get; set; }

    public int? TotalDays { get; set; }

    public Guid? CreatedBy { get; set; }

    public bool? IsDynamicGenerated { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Overview { get; set; }

    public string Objectives { get; set; }

    public string Prerequisites { get; set; }

    public string TechnicalRequirements { get; set; }

    public string SelfAssessmentChecklist { get; set; }

    public virtual ICollection<Week> Weeks { get; set; } = new List<Week>();
}