// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class LearningEvent
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string EventType { get; set; }

    public string EntityType { get; set; }

    public Guid? EntityId { get; set; }

    public string Metadata { get; set; }

    public DateTime? CreatedOn { get; set; }
}