// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Lesson
{
    public Guid LessonId { get; set; }

    public Guid ModuleId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string LessonType { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Overview { get; set; }

    public string Prerequisites { get; set; }

    public int? DurationMinutes { get; set; }

    public bool? IsAiGenerated { get; set; }

    public string Metadata { get; set; }

    public virtual Module Module { get; set; }

    public virtual ICollection<UserModuleProgress> UserModuleProgresses { get; set; } = new List<UserModuleProgress>();
}