// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Module
{
    public Guid ModuleId { get; set; }

    public Guid WeekId { get; set; }

    public string ModuleName { get; set; }

    public string Description { get; set; }

    public int? OrderNo { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Overview { get; set; }

    public string Description1 { get; set; }

    public string Prerequisites { get; set; }

    public int? DurationDays { get; set; }

    public bool? IsAiGenerated { get; set; }

    public string Metadata { get; set; }

    public virtual ICollection<Assessment> Assessments { get; set; } = new List<Assessment>();

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<Resource> Resources { get; set; } = new List<Resource>();

    public virtual Week Week { get; set; }
}