// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class ProblemTestCase
{
    public Guid TestCaseId { get; set; }

    public Guid ProblemId { get; set; }

    public string Input { get; set; }

    public string ExpectedOutput { get; set; }

    public virtual ChallengeProblem Problem { get; set; }
}