// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Resource
{
    public Guid ResourceId { get; set; }

    public Guid TopicId { get; set; }

    public string Title { get; set; }

    public string Url { get; set; }

    public string ResourceType { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? ModuleId { get; set; }

    public string Description { get; set; }

    public bool? IsAiGenerated { get; set; }

    public string Metadata { get; set; }

    public virtual Module Module { get; set; }
}