// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class TeamTask
{
    public Guid TaskId { get; set; }

    public Guid TeamId { get; set; }

    public string Title { get; set; }

    public string Status { get; set; }

    public Guid? AssignedTo { get; set; }

    public virtual User AssignedToNavigation { get; set; }

    public virtual Team Team { get; set; }
}