// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Team
{
    public Guid TeamId { get; set; }

    public Guid? EventId { get; set; }

    public string TeamName { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<AiConversation> AiConversations { get; set; } = new List<AiConversation>();

    public virtual ICollection<AiInsight> AiInsights { get; set; } = new List<AiInsight>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<EventKnowledgeItem> EventKnowledgeItems { get; set; } = new List<EventKnowledgeItem>();

    public virtual ICollection<IdeaSubmission> IdeaSubmissions { get; set; } = new List<IdeaSubmission>();

    public virtual ICollection<JuryFinalScore> JuryFinalScores { get; set; } = new List<JuryFinalScore>();

    public virtual ICollection<Mentor> Mentors { get; set; } = new List<Mentor>();

    public virtual ICollection<Presentation> Presentations { get; set; } = new List<Presentation>();

    public virtual ICollection<TeamFeedbackReply> TeamFeedbackReplies { get; set; } = new List<TeamFeedbackReply>();

    public virtual ICollection<TeamFeedback> TeamFeedbacks { get; set; } = new List<TeamFeedback>();

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();

    public virtual ICollection<TeamTask> TeamTasks { get; set; } = new List<TeamTask>();
}