// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class TeamChatMessage
{
    public Guid MessageId { get; set; }

    public Guid TeamId { get; set; }

    public Guid SenderId { get; set; }

    public string SenderName { get; set; }

    public string MessageText { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? EditedOn { get; set; }

    public bool IsDeleted { get; set; }
}