// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class TeamMember
{
    public Guid TeamMemberId { get; set; }

    public Guid TeamId { get; set; }

    public Guid UserId { get; set; }

    public string Role { get; set; }

    public DateTime? JoinedOn { get; set; }

    public virtual Team Team { get; set; }

    public virtual User User { get; set; }
}