// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class TeamFeedbackReply
{
    public Guid ReplyId { get; set; }

    public Guid FeedbackId { get; set; }

    public Guid TeamId { get; set; }

    public Guid UserId { get; set; }

    public string ReplyText { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? EditedOn { get; set; }

    public bool IsDeleted { get; set; }

    public virtual TeamFeedback Feedback { get; set; }

    public virtual Team Team { get; set; }

    public virtual User User { get; set; }
}