// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class UserAssessmentProgress
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid AssessmentId { get; set; }

    public Guid ModuleId { get; set; }

    public string Status { get; set; }

    public int? Attempts { get; set; }

    public decimal? Score { get; set; }

    public bool? Passed { get; set; }

    public DateTime? StartedOn { get; set; }

    public DateTime? CompletedOn { get; set; }
}