// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class UserLearningPlan
{
    public Guid UserLearningPlanId { get; set; }

    public Guid UserId { get; set; }

    public Guid PlanId { get; set; }

    public Guid AssignedBy { get; set; }

    public DateTime? AssignedOn { get; set; }

    public string Status { get; set; }

    public DateTime? StartedOn { get; set; }

    public DateTime? CompletedOn { get; set; }

    public decimal? ProgressPercent { get; set; }
}