// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class UserSkill
{
    public Guid UserSkillId { get; set; }

    public Guid UserId { get; set; }

    public Guid SkillId { get; set; }

    public double? Proficiency { get; set; }

    public virtual Skill Skill { get; set; }

    public virtual User User { get; set; }
}