// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class User
{
    public Guid UserId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public string PasswordHash { get; set; }

    public Guid? DepartmentId { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual ICollection<AiConversation> AiConversations { get; set; } = new List<AiConversation>();

    public virtual ICollection<AiInsight> AiInsights { get; set; } = new List<AiInsight>();

    public virtual ICollection<Announcement> Announcements { get; set; } = new List<Announcement>();

    public virtual ICollection<Attachment> AttachmentCreatedByNavigations { get; set; } = new List<Attachment>();

    public virtual ICollection<Attachment> AttachmentUpdatedByNavigations { get; set; } = new List<Attachment>();

    public virtual ICollection<Badge> BadgeCreatedByNavigations { get; set; } = new List<Badge>();

    public virtual ICollection<Badge> BadgeUpdatedByNavigations { get; set; } = new List<Badge>();

    public virtual ICollection<Category> CategoryCreatedByNavigations { get; set; } = new List<Category>();

    public virtual ICollection<Category> CategoryUpdatedByNavigations { get; set; } = new List<Category>();

    public virtual ICollection<CodeSubmission> CodeSubmissions { get; set; } = new List<CodeSubmission>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Department> DepartmentCreatedByNavigations { get; set; } = new List<Department>();

    public virtual ICollection<Department> DepartmentHeads { get; set; } = new List<Department>();

    public virtual ICollection<Department> DepartmentUpdatedByNavigations { get; set; } = new List<Department>();

    public virtual ICollection<Domains> DomainCreatedByNavigations { get; set; } = new List<Domains>();

    public virtual ICollection<Domains> DomainUpdatedByNavigations { get; set; } = new List<Domains>();

    public virtual ICollection<Engagement> EngagementCreatedByNavigations { get; set; } = new List<Engagement>();

    public virtual ICollection<Engagement> EngagementUpdatedByNavigations { get; set; } = new List<Engagement>();

    public virtual ICollection<Engagement> EngagementUsers { get; set; } = new List<Engagement>();

    public virtual ICollection<Event> EventCreatedByNavigations { get; set; } = new List<Event>();

    public virtual ICollection<EventJury> EventJuries { get; set; } = new List<EventJury>();

    public virtual ICollection<EventKnowledgeItem> EventKnowledgeItemCreatedByNavigations { get; set; } = new List<EventKnowledgeItem>();

    public virtual ICollection<EventKnowledgeItem> EventKnowledgeItemUpdatedByNavigations { get; set; } = new List<EventKnowledgeItem>();

    public virtual ICollection<Event> EventOwners { get; set; } = new List<Event>();

    public virtual ICollection<Event> EventUpdatedByNavigations { get; set; } = new List<Event>();

    public virtual ICollection<InterviewSession> InterviewSessions { get; set; } = new List<InterviewSession>();

    public virtual ICollection<User> InverseCreatedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<User> InverseUpdatedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<JuryChatMessage> JuryChatMessages { get; set; } = new List<JuryChatMessage>();

    public virtual ICollection<JuryFinalScore> JuryFinalScores { get; set; } = new List<JuryFinalScore>();

    public virtual ICollection<KnowledgeItem> KnowledgeItemCreatedByNavigations { get; set; } = new List<KnowledgeItem>();

    public virtual ICollection<KnowledgeItem> KnowledgeItemOwners { get; set; } = new List<KnowledgeItem>();

    public virtual ICollection<KnowledgeItem> KnowledgeItemUpdatedByNavigations { get; set; } = new List<KnowledgeItem>();

    public virtual ICollection<KnowledgeReviewerAssignment> KnowledgeReviewerAssignmentAssignedByNavigations { get; set; } = new List<KnowledgeReviewerAssignment>();

    public virtual ICollection<KnowledgeReviewerAssignment> KnowledgeReviewerAssignmentReviewers { get; set; } = new List<KnowledgeReviewerAssignment>();

    public virtual ICollection<KnowledgeReview> KnowledgeReviews { get; set; } = new List<KnowledgeReview>();

    public virtual ICollection<KnowledgeTag> KnowledgeTagCreatedByNavigations { get; set; } = new List<KnowledgeTag>();

    public virtual ICollection<KnowledgeTag> KnowledgeTagUpdatedByNavigations { get; set; } = new List<KnowledgeTag>();

    public virtual ICollection<KnowledgeVersion> KnowledgeVersions { get; set; } = new List<KnowledgeVersion>();

    public virtual ICollection<Leaderboard> Leaderboards { get; set; } = new List<Leaderboard>();

    public virtual ICollection<Mentor> Mentors { get; set; } = new List<Mentor>();

    public virtual ICollection<PasswordReset> PasswordResets { get; set; } = new List<PasswordReset>();

    public virtual ICollection<Role> RoleCreatedByNavigations { get; set; } = new List<Role>();

    public virtual ICollection<Role> RoleUpdatedByNavigations { get; set; } = new List<Role>();

    public virtual ICollection<SpotlightItem> SpotlightItems { get; set; } = new List<SpotlightItem>();

    public virtual ICollection<TeamFeedbackReply> TeamFeedbackReplies { get; set; } = new List<TeamFeedbackReply>();

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();

    public virtual ICollection<TeamTask> TeamTasks { get; set; } = new List<TeamTask>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();

    public virtual ICollection<Topic> TopicCreatedByNavigations { get; set; } = new List<Topic>();

    public virtual ICollection<Topic> TopicUpdatedByNavigations { get; set; } = new List<Topic>();

    public virtual User UpdatedByNavigation { get; set; }

    public virtual ICollection<UserAssessmentResult> UserAssessmentResults { get; set; } = new List<UserAssessmentResult>();

    public virtual ICollection<UserRole> UserRoleCreatedByNavigations { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUpdatedByNavigations { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<UserSkill> UserSkills { get; set; } = new List<UserSkill>();
}