// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class UserAssessmentResult
{
    public Guid ResultId { get; set; }

    public Guid UserId { get; set; }

    public Guid AssessmentId { get; set; }

    public string UserAnswers { get; set; }

    public double ScorePercentage { get; set; }

    public bool Passed { get; set; }

    public bool IsCompleted { get; set; }

    public DateTime AttemptedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual User User { get; set; }
}