// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Week
{
    public Guid WeekId { get; set; }

    public Guid PlanId { get; set; }

    public int WeekNumber { get; set; }

    public string Prerequisites { get; set; }

    public string LearningObjectives { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string Metadata { get; set; }

    public bool? IsAiGenerated { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Module> Modules { get; set; } = new List<Module>();

    public virtual LearningPlan Plan { get; set; }
}