// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

using Knowledge_Repository.Domain.Entities;
namespace Knowledge_Repository.Infrastructure.Data;
public partial class Knowledge_Repository_dbContext : DbContext
{
    public Knowledge_Repository_dbContext(DbContextOptions<Knowledge_Repository_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<AiConversation> AiConversations { get; set; }

    public virtual DbSet<AiInsight> AiInsights { get; set; }

    public virtual DbSet<Announcement> Announcements { get; set; }

    public virtual DbSet<Assessment> Assessments { get; set; }

    public virtual DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<Attachment> Attachments { get; set; }

    public virtual DbSet<Badge> Badges { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<ChallengeProblem> ChallengeProblems { get; set; }

    public virtual DbSet<CodeSubmission> CodeSubmissions { get; set; }

    public virtual DbSet<CodingChallenge> CodingChallenges { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Domains> Domains { get; set; }

    public virtual DbSet<Engagement> Engagements { get; set; }

    public virtual DbSet<EvaluationCriterion> EvaluationCriteria { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<EventJury> EventJuries { get; set; }

    public virtual DbSet<EventKnowledgeItem> EventKnowledgeItems { get; set; }

    public virtual DbSet<IdeaSubmission> IdeaSubmissions { get; set; }

    public virtual DbSet<InterviewSession> InterviewSessions { get; set; }

    public virtual DbSet<JuryChatMessage> JuryChatMessages { get; set; }

    public virtual DbSet<JuryFinalScore> JuryFinalScores { get; set; }

    public virtual DbSet<JuryScoreDetail> JuryScoreDetails { get; set; }

    public virtual DbSet<KnowledgeItem> KnowledgeItems { get; set; }

    public virtual DbSet<KnowledgeReview> KnowledgeReviews { get; set; }

    public virtual DbSet<KnowledgeReviewerAssignment> KnowledgeReviewerAssignments { get; set; }

    public virtual DbSet<KnowledgeTag> KnowledgeTags { get; set; }

    public virtual DbSet<KnowledgeVersion> KnowledgeVersions { get; set; }

    public virtual DbSet<Leaderboard> Leaderboards { get; set; }

    public virtual DbSet<LearningEvent> LearningEvents { get; set; }

    public virtual DbSet<LearningPlan> LearningPlans { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    public virtual DbSet<Mentor> Mentors { get; set; }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<PasswordReset> PasswordResets { get; set; }

    public virtual DbSet<Presentation> Presentations { get; set; }

    public virtual DbSet<ProblemTestCase> ProblemTestCases { get; set; }

    public virtual DbSet<Resource> Resources { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<SpotlightItem> SpotlightItems { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamChatMessage> TeamChatMessages { get; set; }

    public virtual DbSet<TeamFeedback> TeamFeedbacks { get; set; }

    public virtual DbSet<TeamFeedbackReply> TeamFeedbackReplies { get; set; }

    public virtual DbSet<TeamMember> TeamMembers { get; set; }

    public virtual DbSet<TeamTask> TeamTasks { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAssessmentProgress> UserAssessmentProgresses { get; set; }

    public virtual DbSet<UserAssessmentResult> UserAssessmentResults { get; set; }

    public virtual DbSet<UserLearningPlan> UserLearningPlans { get; set; }

    public virtual DbSet<UserLessonProgress> UserLessonProgresses { get; set; }

    public virtual DbSet<UserModuleProgress> UserModuleProgresses { get; set; }

    public virtual DbSet<UserPlanEnrollment> UserPlanEnrollments { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserSkill> UserSkills { get; set; }

    public virtual DbSet<Week> Weeks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("activity_action_enum", new[] { "Upload", "Approve", "Reject", "Comment", "Like", "Event Created", "UploadKnowledgeItem" })
            .HasPostgresEnum("announcement_priority_enum", new[] { "Urgent", "Reminder", "Info" })
            .HasPostgresEnum("engagement_action_enum", new[] { "View", "Like", "Comment", "Share" })
            .HasPostgresEnum("event_type_enum", new[] { "Ideathon", "Hackathon", "Coding Challenge", "Knowledge Quest" })
            .HasPostgresEnum("file_type_enum", new[] { "File", "Text", "Video", "Audio" })
            .HasPostgresEnum("knowledge_status_enum", new[] { "Draft", "Submitted", "Under Review", "Approved", "Rejected", "Archived" })
            .HasPostgresEnum("leaderboard_category_enum", new[] { "Overall", "Domain Experts", "Rising Stars", "Event Champions" })
            .HasPostgresEnum("leaderboard_period_enum", new[] { "Daily", "Weekly", "Monthly" })
            .HasPostgresEnum("participant_status_enum", new[] { "Registered", "Checked-in", "Cancelled" })
            .HasPostgresEnum("presentation_type_enum", new[] { "Live", "Recorded" })
            .HasPostgresEnum("review_status_enum", new[] { "Reviewed", "Approved", "Rejected", "Revision Requested" })
            .HasPostgresEnum("reviewer_assignment_status_enum", new[] { "Pending", "Cancelled", "Reassigned" })
            .HasPostgresEnum("role_name_enum", new[] { "Contributor", "Reviewer", "Approver", "Admin", "Reader" })
            .HasPostgresEnum("spotlight_type_enum", new[] { "quote", "text" })
            .HasPostgresEnum("submission_status_enum", new[] { "Submitted", "Reviewed", "Selected", "Winner" })
            .HasPostgresEnum("team_member_role_enum", new[] { "Leader", "Member" })
            .HasPostgresEnum("visibility_enum", new[] { "Public", "Department-Restricted", "Private" })
            .HasPostgresExtension("pgcrypto")
            .HasPostgresExtension("uuid-ossp")
            .HasPostgresExtension("vector");

        modelBuilder.Entity<ActivityLog>(entity =>
        {
            entity.HasKey(e => e.ActivityId).HasName("activity_log_pkey");

            entity.ToTable("activity_log");

            entity.Property(e => e.ActivityId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("activity_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Details).HasColumnName("details");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Event).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("activity_log_event_id_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("activity_log_item_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("activity_log_user_id_fkey");
        });

        modelBuilder.Entity<AiConversation>(entity =>
        {
            entity.HasKey(e => e.ConversationId).HasName("ai_conversations_pkey");

            entity.ToTable("ai_conversations");

            entity.Property(e => e.ConversationId)
                .ValueGeneratedNever()
                .HasColumnName("conversation_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.Role).HasColumnName("role");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Event).WithMany(p => p.AiConversations)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("ai_conversations_event_id_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.AiConversations)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("ai_conversations_team_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.AiConversations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ai_conversations_user_id_fkey");
        });

        modelBuilder.Entity<AiInsight>(entity =>
        {
            entity.HasKey(e => e.AiInsightId).HasName("ai_insights_pkey");

            entity.ToTable("ai_insights");

            entity.Property(e => e.AiInsightId)
                .ValueGeneratedNever()
                .HasColumnName("ai_insight_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.EntityId).HasColumnName("entity_id");
            entity.Property(e => e.EntityType).HasColumnName("entity_type");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.InputContext).HasColumnName("input_context");
            entity.Property(e => e.InsightType).HasColumnName("insight_type");
            entity.Property(e => e.OutputResult).HasColumnName("output_result");
            entity.Property(e => e.Score).HasColumnName("score");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Event).WithMany(p => p.AiInsights)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("ai_insights_event_id_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.AiInsights)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("ai_insights_team_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.AiInsights)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("ai_insights_user_id_fkey");
        });

        modelBuilder.Entity<Announcement>(entity =>
        {
            entity.HasKey(e => e.AnnouncementId).HasName("announcements_pkey");

            entity.ToTable("announcements");

            entity.Property(e => e.AnnouncementId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("announcement_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Announcements)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("announcements_created_by_fkey");
        });

        modelBuilder.Entity<Assessment>(entity =>
        {
            entity.HasKey(e => e.AssessmentId).HasName("assessments_pkey");

            entity.ToTable("assessments");

            entity.HasIndex(e => e.ModuleId, "idx_assessment_module");

            entity.HasIndex(e => e.TopicId, "idx_assessments_topic_id");

            entity.HasIndex(e => e.WeekId, "idx_assessments_week_id");

            entity.Property(e => e.AssessmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("assessment_id");
            entity.Property(e => e.AssessmentScope)
                .HasMaxLength(20)
                .HasDefaultValueSql("'LESSON'::character varying")
                .HasColumnName("assessment_scope");
            entity.Property(e => e.AssessmentType)
                .HasMaxLength(50)
                .HasColumnName("assessment_type");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Difficulty).HasColumnName("difficulty");
            entity.Property(e => e.EstimatedDurationMinutes).HasColumnName("estimated_duration_minutes");
            entity.Property(e => e.IsAiGenerated)
                .HasDefaultValue(false)
                .HasColumnName("is_ai_generated");
            entity.Property(e => e.LearningObjectives).HasColumnName("learning_objectives");
            entity.Property(e => e.Metadata)
                .HasColumnType("jsonb")
                .HasColumnName("metadata");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.SkillsTested)
                .HasColumnType("jsonb")
                .HasColumnName("skills_tested");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.TopicId).HasColumnName("topic_id");
            entity.Property(e => e.TotalMarks).HasColumnName("total_marks");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_on");
            entity.Property(e => e.WeekId).HasColumnName("week_id");

            entity.HasOne(d => d.Module).WithMany(p => p.Assessments)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_assessment_module");

            entity.HasOne(d => d.Week).WithMany(p => p.Assessments)
                .HasForeignKey(d => d.WeekId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_assessment_week");
        });

        modelBuilder.Entity<AssessmentQuestion>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("assessment_questions_pkey");

            entity.ToTable("assessment_questions");

            entity.HasIndex(e => e.AssessmentId, "idx_question_assessment");

            entity.HasIndex(e => e.AssessmentId, "idx_questions_assessment_id");

            entity.Property(e => e.QuestionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("question_id");
            entity.Property(e => e.AssessmentId).HasColumnName("assessment_id");
            entity.Property(e => e.CorrectAnswer).HasColumnName("correct_answer");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.EvaluationStrategy)
                .HasMaxLength(50)
                .HasColumnName("evaluation_strategy");
            entity.Property(e => e.Explanation).HasColumnName("explanation");
            entity.Property(e => e.Hint1).HasColumnName("hint");
            entity.Property(e => e.IsAiGenerated)
                .HasDefaultValue(false)
                .HasColumnName("is_ai_generated");
            entity.Property(e => e.Marks)
                .HasDefaultValue(1)
                .HasColumnName("marks");
            entity.Property(e => e.Metadata)
                .HasColumnType("jsonb")
                .HasColumnName("metadata");
            entity.Property(e => e.Options)
                .HasColumnType("jsonb")
                .HasColumnName("options");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasColumnName("question");
            entity.Property(e => e.QuestionType)
                .HasMaxLength(50)
                .HasColumnName("question_type");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_on");

            entity.HasOne(d => d.Assessment).WithMany(p => p.AssessmentQuestions)
                .HasForeignKey(d => d.AssessmentId)
                .HasConstraintName("assessment_questions_assessment_id_fkey");
        });

        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("assignments_pkey");

            entity.ToTable("assignments");

            entity.HasIndex(e => e.TopicId, "idx_assignments_topic_id");

            entity.HasIndex(e => e.WeekId, "idx_assignments_week_id");

            entity.Property(e => e.AssignmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("assignment_id");
            entity.Property(e => e.AssignmentType)
                .HasMaxLength(50)
                .HasColumnName("assignment_type");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EstimatedDurationMinutes).HasColumnName("estimated_duration_minutes");
            entity.Property(e => e.ExpectedOutput).HasColumnName("expected_output");
            entity.Property(e => e.GradingStrategy)
                .HasMaxLength(50)
                .HasColumnName("grading_strategy");
            entity.Property(e => e.Metadata)
                .HasColumnType("jsonb")
                .HasColumnName("metadata");
            entity.Property(e => e.RubricJson)
                .HasColumnType("jsonb")
                .HasColumnName("rubric_json");
            entity.Property(e => e.SkillsEvaluated)
                .HasColumnType("jsonb")
                .HasColumnName("skills_evaluated");
            entity.Property(e => e.SubmissionFormat)
                .HasMaxLength(50)
                .HasColumnName("submission_format");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.TopicId).HasColumnName("topic_id");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_on");
            entity.Property(e => e.WeekId).HasColumnName("week_id");

            entity.HasOne(d => d.Week).WithMany(p => p.Assignments)
                .HasForeignKey(d => d.WeekId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("assignments_week_id_fkey");
        });

        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.HasKey(e => e.AttachmentId).HasName("attachments_pkey");

            entity.ToTable("attachments");

            entity.Property(e => e.AttachmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("attachment_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.FileData).HasColumnName("file_data");
            entity.Property(e => e.FileName).HasColumnName("file_name");
            entity.Property(e => e.FilePath).HasColumnName("file_path");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.FileType).HasColumnName("file_type");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.MimeType).HasColumnName("mime_type");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.VersionId).HasColumnName("version_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.AttachmentCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("attachments_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("attachments_item_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.AttachmentUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("attachments_updated_by_fkey");

            entity.HasOne(d => d.Version).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("attachments_version_id_fkey");
        });

        modelBuilder.Entity<Badge>(entity =>
        {
            entity.HasKey(e => e.BadgeId).HasName("badges_pkey");

            entity.ToTable("badges");

            entity.HasIndex(e => e.BadgeName, "badges_badge_name_key").IsUnique();

            entity.Property(e => e.BadgeId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("badge_id");
            entity.Property(e => e.BadgeName)
                .IsRequired()
                .HasColumnName("badge_name");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IconUrl).HasColumnName("icon_url");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.BadgeCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("badges_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.BadgeUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("badges_updated_by_fkey");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("categories_pkey");

            entity.ToTable("categories");

            entity.HasIndex(e => new { e.CategoryName, e.DomainId }, "categories_category_name_domain_id_key").IsUnique();

            entity.Property(e => e.CategoryId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("category_id");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasColumnName("category_name");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DomainId).HasColumnName("domain_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CategoryCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("categories_created_by_fkey");

            entity.HasOne(d => d.Domain).WithMany(p => p.Categories)
                .HasForeignKey(d => d.DomainId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("categories_domain_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.CategoryUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("categories_updated_by_fkey");
        });

        modelBuilder.Entity<ChallengeProblem>(entity =>
        {
            entity.HasKey(e => e.ProblemId).HasName("challenge_problems_pkey");

            entity.ToTable("challenge_problems");

            entity.Property(e => e.ProblemId)
                .ValueGeneratedNever()
                .HasColumnName("problem_id");
            entity.Property(e => e.ChallengeId).HasColumnName("challenge_id");
            entity.Property(e => e.ProblemStatement)
                .IsRequired()
                .HasColumnName("problem_statement");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");

            entity.HasOne(d => d.Challenge).WithMany(p => p.ChallengeProblems)
                .HasForeignKey(d => d.ChallengeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("challenge_problems_challenge_id_fkey");
        });

        modelBuilder.Entity<CodeSubmission>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("code_submissions_pkey");

            entity.ToTable("code_submissions");

            entity.Property(e => e.SubmissionId)
                .ValueGeneratedNever()
                .HasColumnName("submission_id");
            entity.Property(e => e.Language).HasColumnName("language");
            entity.Property(e => e.ProblemId).HasColumnName("problem_id");
            entity.Property(e => e.Score).HasColumnName("score");
            entity.Property(e => e.SourceCode)
                .IsRequired()
                .HasColumnName("source_code");
            entity.Property(e => e.SubmittedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("submitted_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Problem).WithMany(p => p.CodeSubmissions)
                .HasForeignKey(d => d.ProblemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("code_submissions_problem_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.CodeSubmissions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("code_submissions_user_id_fkey");
        });

        modelBuilder.Entity<CodingChallenge>(entity =>
        {
            entity.HasKey(e => e.ChallengeId).HasName("coding_challenges_pkey");

            entity.ToTable("coding_challenges");

            entity.Property(e => e.ChallengeId)
                .ValueGeneratedNever()
                .HasColumnName("challenge_id");
            entity.Property(e => e.Difficulty).HasColumnName("difficulty");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.TimeLimitMinutes).HasColumnName("time_limit_minutes");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");

            entity.HasOne(d => d.Event).WithMany(p => p.CodingChallenges)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("coding_challenges_event_id_fkey");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentId).HasName("departments_pkey");

            entity.ToTable("departments");

            entity.HasIndex(e => e.DepartmentName, "departments_department_name_key").IsUnique();

            entity.Property(e => e.DepartmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("department_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.DepartmentName)
                .IsRequired()
                .HasColumnName("department_name");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.HeadId).HasColumnName("head_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DepartmentCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("departments_created_by_fkey");

            entity.HasOne(d => d.Head).WithMany(p => p.DepartmentHeads)
                .HasForeignKey(d => d.HeadId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("departments_head_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.DepartmentUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("departments_updated_by_fkey");
        });

        modelBuilder.Entity<Domains>(entity =>
        {
            entity.HasKey(e => e.DomainId).HasName("domains_pkey");

            entity.ToTable("domains");

            entity.HasIndex(e => e.DomainName, "domains_domain_name_key").IsUnique();

            entity.Property(e => e.DomainId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("domain_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DomainName)
                .IsRequired()
                .HasColumnName("domain_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DomainCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("domains_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.DomainUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("domains_updated_by_fkey");
        });

        modelBuilder.Entity<Engagement>(entity =>
        {
            entity.HasKey(e => e.EngagementId).HasName("engagements_pkey");

            entity.ToTable("engagements");

            entity.Property(e => e.EngagementId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("engagement_id");
            entity.Property(e => e.CommentText).HasColumnName("comment_text");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EngagementType).HasMaxLength(50);
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.ParentCommentId).HasColumnName("parent_comment_id");
            entity.Property(e => e.Points)
                .HasDefaultValue(0)
                .HasColumnName("points");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EngagementCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("engagements_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.Engagements)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("engagements_item_id_fkey");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_engagement_parent_comment");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.EngagementUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("engagements_updated_by_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.EngagementUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("engagements_user_id_fkey");
        });

        modelBuilder.Entity<EvaluationCriterion>(entity =>
        {
            entity.HasKey(e => e.CriteriaId).HasName("evaluation_criteria_pkey");

            entity.ToTable("evaluation_criteria");

            entity.Property(e => e.CriteriaId)
                .ValueGeneratedNever()
                .HasColumnName("criteria_id");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.Weight).HasColumnName("weight");

            entity.HasOne(d => d.Event).WithMany(p => p.EvaluationCriteria)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("evaluation_criteria_event_id_fkey");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("events_pkey");

            entity.ToTable("events");

            entity.Property(e => e.EventId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("event_id");
            entity.Property(e => e.ContactEmail).HasColumnName("contact_email");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasColumnName("event_type");
            entity.Property(e => e.FinalSubmissionDeadline).HasColumnName("final_submission_deadline");
            entity.Property(e => e.IdeaPresentationEnd).HasColumnName("idea_presentation_end");
            entity.Property(e => e.IdeaPresentationStart).HasColumnName("idea_presentation_start");
            entity.Property(e => e.MentorCheckpointEnd).HasColumnName("mentor_checkpoint_end");
            entity.Property(e => e.MentorCheckpointStart).HasColumnName("mentor_checkpoint_start");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.RegistrationCloseDate).HasColumnName("registration_close_date");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.WinnersAnnouncementDate).HasColumnName("winners_announcement_date");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EventCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("events_created_by_fkey");

            entity.HasOne(d => d.Owner).WithMany(p => p.EventOwners)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("events_owner_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.EventUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("events_updated_by_fkey");
        });

        modelBuilder.Entity<EventJury>(entity =>
        {
            entity.HasKey(e => e.EventJuryId).HasName("event_jury_pkey");

            entity.ToTable("event_jury");

            entity.HasIndex(e => new { e.EventId, e.UserId }, "ux_eventjury_event_user").IsUnique();

            entity.Property(e => e.EventJuryId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("event_jury_id");
            entity.Property(e => e.AssignedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("assigned_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Event).WithMany(p => p.EventJuries)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("fk_eventjury_event");

            entity.HasOne(d => d.User).WithMany(p => p.EventJuries)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_eventjury_user");
        });

        modelBuilder.Entity<EventKnowledgeItem>(entity =>
        {
            entity.HasKey(e => e.EventItemId).HasName("event_knowledge_items_pkey");

            entity.ToTable("event_knowledge_items");

            entity.Property(e => e.EventItemId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("event_item_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EventKnowledgeItemCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("event_knowledge_items_created_by_fkey");

            entity.HasOne(d => d.Event).WithMany(p => p.EventKnowledgeItems)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("event_knowledge_items_event_id_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.EventKnowledgeItems)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("event_knowledge_items_item_id_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.EventKnowledgeItems)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("event_knowledge_items_team_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.EventKnowledgeItemUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("event_knowledge_items_updated_by_fkey");
        });

        modelBuilder.Entity<IdeaSubmission>(entity =>
        {
            entity.HasKey(e => e.IdeaId).HasName("idea_submissions_pkey");

            entity.ToTable("idea_submissions");

            entity.HasIndex(e => new { e.TeamId, e.EventId }, "uq_idea_team_event").IsUnique();

            entity.Property(e => e.IdeaId)
                .ValueGeneratedNever()
                .HasColumnName("idea_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.DemoUrl)
                .HasMaxLength(500)
                .HasColumnName("demo_url");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.IdeaDescription)
                .IsRequired()
                .HasColumnName("idea_description");
            entity.Property(e => e.IdeaTitle)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("idea_title");
            entity.Property(e => e.RepoUrl)
                .HasMaxLength(500)
                .HasColumnName("repo_url");
            entity.Property(e => e.TeamId).HasColumnName("team_id");

            entity.HasOne(d => d.Event).WithMany(p => p.IdeaSubmissions)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_idea_event");

            entity.HasOne(d => d.Team).WithMany(p => p.IdeaSubmissions)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_idea_team");
        });

        modelBuilder.Entity<InterviewSession>(entity =>
        {
            entity.HasKey(e => e.InterviewId).HasName("interview_sessions_pkey");

            entity.ToTable("interview_sessions");

            entity.Property(e => e.InterviewId)
                .ValueGeneratedNever()
                .HasColumnName("interview_id");
            entity.Property(e => e.CommunicationScore).HasColumnName("communication_score");
            entity.Property(e => e.CompletedOn)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("completed_on");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.FinalFeedback).HasColumnName("final_feedback");
            entity.Property(e => e.IsCompleted)
                .HasDefaultValue(false)
                .HasColumnName("is_completed");
            entity.Property(e => e.ProblemId).HasColumnName("problem_id");
            entity.Property(e => e.QuestionCount)
                .HasDefaultValue(0)
                .HasColumnName("question_count");
            entity.Property(e => e.Transcript).HasColumnName("transcript");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Problem).WithMany(p => p.InterviewSessions)
                .HasForeignKey(d => d.ProblemId)
                .HasConstraintName("interview_sessions_problem_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.InterviewSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("interview_sessions_user_id_fkey");
        });

        modelBuilder.Entity<JuryChatMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("JuryChatMessage_pkey");

            entity.ToTable("JuryChatMessage");

            entity.Property(e => e.MessageId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.Message).IsRequired();

            entity.HasOne(d => d.Event).WithMany(p => p.JuryChatMessages)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK_JuryChatMessage_Event");

            entity.HasOne(d => d.ReplyToMessage).WithMany(p => p.InverseReplyToMessage)
                .HasForeignKey(d => d.ReplyToMessageId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_JuryChatMessage_ReplyToMessage");

            entity.HasOne(d => d.SenderJury).WithMany(p => p.JuryChatMessages)
                .HasForeignKey(d => d.SenderJuryId)
                .HasConstraintName("FK_JuryChatMessage_SenderJury");
        });

        modelBuilder.Entity<JuryFinalScore>(entity =>
        {
            entity.HasKey(e => e.FinalId).HasName("JuryFinalScore_pkey");

            entity.ToTable("JuryFinalScore");

            entity.Property(e => e.FinalId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.ApprovedOn).HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.JuryFinalScores)
                .HasForeignKey(d => d.ApprovedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_JuryFinalScore_User");

            entity.HasOne(d => d.Event).WithMany(p => p.JuryFinalScores)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK_JuryFinalScore_Event");

            entity.HasOne(d => d.Team).WithMany(p => p.JuryFinalScores)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_JuryFinalScore_Team");
        });

        modelBuilder.Entity<JuryScoreDetail>(entity =>
        {
            entity.HasKey(e => e.ScoreDetailId).HasName("JuryScoreDetails_pkey");

            entity.Property(e => e.ScoreDetailId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CriteriaName).IsRequired();

            entity.HasOne(d => d.Final).WithMany(p => p.JuryScoreDetails)
                .HasForeignKey(d => d.FinalId)
                .HasConstraintName("FK_JuryScoreDetails_Final");
        });

        modelBuilder.Entity<KnowledgeItem>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("knowledge_items_pkey");

            entity.ToTable("knowledge_items");

            entity.Property(e => e.ItemId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("item_id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DomainId).HasColumnName("domain_id");
            entity.Property(e => e.Framework)
                .HasColumnType("jsonb")
                .HasColumnName("framework");
            entity.Property(e => e.IsEventItem)
                .HasDefaultValue(false)
                .HasColumnName("is_event_item");
            entity.Property(e => e.KnowledgeText).HasColumnName("knowledge_text");
            entity.Property(e => e.Language)
                .HasColumnType("jsonb")
                .HasColumnName("language");
            entity.Property(e => e.Metadata)
                .HasColumnType("jsonb")
                .HasColumnName("metadata");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'Draft'::knowledge_status_enum")
                .HasColumnName("status");
            entity.Property(e => e.Title).HasColumnName("title");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.Version)
                .HasDefaultValue(1)
                .HasColumnName("version");

            entity.HasOne(d => d.Category).WithMany(p => p.KnowledgeItems)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_category_id_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.KnowledgeItemCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_created_by_fkey");

            entity.HasOne(d => d.Domain).WithMany(p => p.KnowledgeItems)
                .HasForeignKey(d => d.DomainId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_domain_id_fkey");

            entity.HasOne(d => d.Owner).WithMany(p => p.KnowledgeItemOwners)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_owner_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.KnowledgeItemUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_updated_by_fkey");
        });

        modelBuilder.Entity<KnowledgeReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("knowledge_reviews_pkey");

            entity.ToTable("knowledge_reviews");

            entity.Property(e => e.ReviewId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("review_id");
            entity.Property(e => e.AssignmentId).HasColumnName("assignment_id");
            entity.Property(e => e.Decision).HasMaxLength(50);
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.ReviewedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("reviewed_on");
            entity.Property(e => e.ReviewerId).HasColumnName("reviewer_id");

            entity.HasOne(d => d.Assignment).WithMany(p => p.KnowledgeReviews)
                .HasForeignKey(d => d.AssignmentId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_reviews_assignment_id_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeReviews)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_reviews_item_id_fkey");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.KnowledgeReviews)
                .HasForeignKey(d => d.ReviewerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_reviews_reviewer_id_fkey");
        });

        modelBuilder.Entity<KnowledgeReviewerAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("knowledge_reviewer_assignments_pkey");

            entity.ToTable("knowledge_reviewer_assignments");

            entity.Property(e => e.AssignmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("assignment_id");
            entity.Property(e => e.AssignedBy).HasColumnName("assigned_by");
            entity.Property(e => e.AssignedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("assigned_on");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.ReviewerId).HasColumnName("reviewer_id");

            entity.HasOne(d => d.AssignedByNavigation).WithMany(p => p.KnowledgeReviewerAssignmentAssignedByNavigations)
                .HasForeignKey(d => d.AssignedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_reviewer_assignments_assigned_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeReviewerAssignments)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_reviewer_assignments_item_id_fkey");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.KnowledgeReviewerAssignmentReviewers)
                .HasForeignKey(d => d.ReviewerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_reviewer_assignments_reviewer_id_fkey");
        });

        modelBuilder.Entity<KnowledgeTag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("knowledge_tags_pkey");

            entity.ToTable("knowledge_tags");

            entity.HasIndex(e => new { e.ItemId, e.TagName, e.VersionId }, "knowledge_tags_item_id_tag_name_version_id_key").IsUnique();

            entity.Property(e => e.TagId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("tag_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasColumnName("tag_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.VersionId).HasColumnName("version_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.KnowledgeTagCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_tags_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeTags)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_tags_item_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.KnowledgeTagUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_tags_updated_by_fkey");

            entity.HasOne(d => d.Version).WithMany(p => p.KnowledgeTags)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_tags_version_id_fkey");
        });

        modelBuilder.Entity<KnowledgeVersion>(entity =>
        {
            entity.HasKey(e => e.VersionId).HasName("knowledge_versions_pkey");

            entity.ToTable("knowledge_versions");

            entity.HasIndex(e => new { e.ItemId, e.VersionNumber }, "knowledge_versions_item_id_version_number_key").IsUnique();

            entity.Property(e => e.VersionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("version_id");
            entity.Property(e => e.ChangesSummary).HasColumnName("changes_summary");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.FilePath).HasColumnName("file_path");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.VersionNumber).HasColumnName("version_number");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.KnowledgeVersions)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_versions_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeVersions)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("knowledge_versions_item_id_fkey");
        });

        modelBuilder.Entity<Leaderboard>(entity =>
        {
            entity.HasKey(e => e.LeaderboardId).HasName("leaderboards_pkey");

            entity.ToTable("leaderboards");

            entity.Property(e => e.LeaderboardId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("leaderboard_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Points)
                .HasDefaultValue(0)
                .HasColumnName("points");
            entity.Property(e => e.Rank).HasColumnName("rank");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Leaderboards)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("leaderboards_user_id_fkey");
        });

        modelBuilder.Entity<LearningEvent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("learning_events_pkey");

            entity.ToTable("learning_events");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EntityId).HasColumnName("entity_id");
            entity.Property(e => e.EntityType)
                .HasMaxLength(50)
                .HasColumnName("entity_type");
            entity.Property(e => e.EventType)
                .HasMaxLength(50)
                .HasColumnName("event_type");
            entity.Property(e => e.Metadata)
                .HasColumnType("jsonb")
                .HasColumnName("metadata");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<LearningPlan>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("learning_plans_pkey");

            entity.ToTable("learning_plans");

            entity.Property(e => e.PlanId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("plan_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DurationWeeks).HasColumnName("duration_weeks");
            entity.Property(e => e.IsDynamicGenerated)
                .HasDefaultValue(false)
                .HasColumnName("is_dynamic_generated");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.TotalDays).HasColumnName("total_days");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_on");
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.LessonId).HasName("lessons_pkey");

            entity.ToTable("lessons");

            entity.HasIndex(e => e.ModuleId, "idx_lesson_module");

            entity.HasIndex(e => e.ModuleId, "idx_lessons_module_id");

            entity.Property(e => e.LessonId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("lesson_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.IsAiGenerated).HasDefaultValue(false);
            entity.Property(e => e.LessonType)
                .HasMaxLength(50)
                .HasColumnName("lesson_type");
            entity.Property(e => e.Metadata).HasColumnType("jsonb");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.OrderIndex).HasColumnName("order_index");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_on");

            entity.HasOne(d => d.Module).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("fk_lesson_module");
        });

        modelBuilder.Entity<Mentor>(entity =>
        {
            entity.HasKey(e => e.MentorId).HasName("mentors_pkey");

            entity.ToTable("mentors");

            entity.Property(e => e.MentorId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("mentor_id");
            entity.Property(e => e.AssignedTeamId).HasColumnName("assigned_team_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.AssignedTeam).WithMany(p => p.Mentors)
                .HasForeignKey(d => d.AssignedTeamId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("mentors_assigned_team_id_fkey");

            entity.HasOne(d => d.Event).WithMany(p => p.Mentors)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("mentors_event_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.Mentors)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("mentors_user_id_fkey");
        });

        modelBuilder.Entity<Module>(entity =>
        {
            entity.HasKey(e => e.ModuleId).HasName("module_pkey");

            entity.ToTable("module");

            entity.HasIndex(e => e.WeekId, "idx_module_week");

            entity.Property(e => e.ModuleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("module_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Description1).HasColumnName("Description");
            entity.Property(e => e.IsAiGenerated).HasDefaultValue(false);
            entity.Property(e => e.ModuleName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("module_name");
            entity.Property(e => e.OrderNo).HasColumnName("order_no");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_on");
            entity.Property(e => e.WeekId).HasColumnName("week_id");

            entity.HasOne(d => d.Week).WithMany(p => p.Modules)
                .HasForeignKey(d => d.WeekId)
                .HasConstraintName("fk_module_week");
        });

        modelBuilder.Entity<PasswordReset>(entity =>
        {
            entity.HasKey(e => e.PasswordResetId).HasName("PasswordReset_pkey");

            entity.ToTable("PasswordReset");

            entity.Property(e => e.PasswordResetId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CodeExpiresAt).HasColumnType("timestamp without time zone");
            entity.Property(e => e.CodeHash).IsRequired();
            entity.Property(e => e.CodeUsed).HasDefaultValue(false);
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.ResetTokenExpiresAt).HasColumnType("timestamp without time zone");
            entity.Property(e => e.ResetTokenUsed).HasDefaultValue(false);
            entity.Property(e => e.UpdatedOn).HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.User).WithMany(p => p.PasswordResets)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PasswordReset_User");
        });

        modelBuilder.Entity<Presentation>(entity =>
        {
            entity.HasKey(e => e.PresentationId).HasName("presentations_pkey");

            entity.ToTable("presentations");

            entity.Property(e => e.PresentationId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("presentation_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.PresentationDate).HasColumnName("presentation_date");
            entity.Property(e => e.Rank).HasColumnName("rank");
            entity.Property(e => e.Score).HasColumnName("score");
            entity.Property(e => e.TeamId).HasColumnName("team_id");

            entity.HasOne(d => d.Event).WithMany(p => p.Presentations)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("presentations_event_id_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.Presentations)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("presentations_team_id_fkey");
        });

        modelBuilder.Entity<ProblemTestCase>(entity =>
        {
            entity.HasKey(e => e.TestCaseId).HasName("problem_test_cases_pkey");

            entity.ToTable("problem_test_cases");

            entity.Property(e => e.TestCaseId)
                .ValueGeneratedNever()
                .HasColumnName("test_case_id");
            entity.Property(e => e.ExpectedOutput)
                .IsRequired()
                .HasColumnName("expected_output");
            entity.Property(e => e.Input)
                .IsRequired()
                .HasColumnName("input");
            entity.Property(e => e.ProblemId).HasColumnName("problem_id");

            entity.HasOne(d => d.Problem).WithMany(p => p.ProblemTestCases)
                .HasForeignKey(d => d.ProblemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("problem_test_cases_problem_id_fkey");
        });

        modelBuilder.Entity<Resource>(entity =>
        {
            entity.HasKey(e => e.ResourceId).HasName("resources_pkey");

            entity.ToTable("resources");

            entity.HasIndex(e => e.ModuleId, "idx_resource_module");

            entity.HasIndex(e => e.TopicId, "idx_resources_topic_id");

            entity.Property(e => e.ResourceId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("resource_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.Difficulty).HasColumnName("difficulty");
            entity.Property(e => e.EstimatedDurationMinutes).HasColumnName("estimated_duration_minutes");
            entity.Property(e => e.IsAiGenerated).HasDefaultValue(false);
            entity.Property(e => e.Metadata).HasColumnType("jsonb");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.ResourceType)
                .HasMaxLength(50)
                .HasColumnName("resource_type");
            entity.Property(e => e.Source)
                .HasMaxLength(100)
                .HasColumnName("source");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.TopicId).HasColumnName("topic_id");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_on");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasColumnName("url");

            entity.HasOne(d => d.Module).WithMany(p => p.Resources)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_resource_module");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("roles_pkey");

            entity.ToTable("roles");

            entity.HasIndex(e => e.RoleName, "roles_role_name_key").IsUnique();

            entity.Property(e => e.RoleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("role_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasColumnName("role_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.RoleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("roles_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.RoleUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("roles_updated_by_fkey");
        });

        modelBuilder.Entity<Skill>(entity =>
        {
            entity.HasKey(e => e.SkillId).HasName("skills_pkey");

            entity.ToTable("skills");

            entity.HasIndex(e => e.Name, "skills_name_key").IsUnique();

            entity.Property(e => e.SkillId)
                .ValueGeneratedNever()
                .HasColumnName("skill_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
        });

        modelBuilder.Entity<SpotlightItem>(entity =>
        {
            entity.HasKey(e => e.SpotlightId).HasName("spotlight_items_pkey");

            entity.ToTable("spotlight_items");

            entity.Property(e => e.SpotlightId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("spotlight_id");
            entity.Property(e => e.ContentText).HasColumnName("content_text");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.ResourceLink).HasColumnName("resource_link");
            entity.Property(e => e.ValidDate).HasColumnName("valid_date");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.SpotlightItems)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("spotlight_items_created_by_fkey");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("teams_pkey");

            entity.ToTable("teams");

            entity.Property(e => e.TeamId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("team_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasColumnName("team_name");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Teams)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("teams_created_by_fkey");

            entity.HasOne(d => d.Event).WithMany(p => p.Teams)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("teams_event_id_fkey");
        });

        modelBuilder.Entity<TeamChatMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("TeamChatMessage_pkey");

            entity.ToTable("TeamChatMessage");

            entity.Property(e => e.MessageId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("now()");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.MessageText).IsRequired();
            entity.Property(e => e.SenderName).IsRequired();
        });

        modelBuilder.Entity<TeamFeedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("team_feedback_pkey");

            entity.ToTable("team_feedback");

            entity.Property(e => e.FeedbackId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("feedback_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.FeedbackText).HasColumnName("feedback_text");
            entity.Property(e => e.LastReplyOn).HasColumnName("last_reply_on");
            entity.Property(e => e.MentorId).HasColumnName("mentor_id");
            entity.Property(e => e.ProgressRating).HasColumnName("progress_rating");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.Event).WithMany(p => p.TeamFeedbacks)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("fk_team_feedback_event");

            entity.HasOne(d => d.Mentor).WithMany(p => p.TeamFeedbacks)
                .HasForeignKey(d => d.MentorId)
                .HasConstraintName("fk_team_feedback_mentor");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamFeedbacks)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("fk_team_feedback_team");
        });

        modelBuilder.Entity<TeamFeedbackReply>(entity =>
        {
            entity.HasKey(e => e.ReplyId);

            entity.ToTable("TeamFeedbackReply");

            entity.Property(e => e.ReplyId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.EditedOn).HasColumnType("timestamp without time zone");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.ReplyText).IsRequired();

            entity.HasOne(d => d.Feedback).WithMany(p => p.TeamFeedbackReplies)
                .HasForeignKey(d => d.FeedbackId)
                .HasConstraintName("FK_TeamFeedbackReply_Feedback");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamFeedbackReplies)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_TeamFeedbackReply_Team");

            entity.HasOne(d => d.User).WithMany(p => p.TeamFeedbackReplies)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_TeamFeedbackReply_User");
        });

        modelBuilder.Entity<TeamMember>(entity =>
        {
            entity.HasKey(e => e.TeamMemberId).HasName("team_members_pkey");

            entity.ToTable("team_members");

            entity.HasIndex(e => new { e.TeamId, e.UserId }, "team_members_team_id_user_id_key").IsUnique();

            entity.Property(e => e.TeamMemberId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("team_member_id");
            entity.Property(e => e.JoinedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("joined_on");
            entity.Property(e => e.Role)
                .IsRequired()
                .HasDefaultValueSql("'Member'::team_member_role_enum")
                .HasColumnName("role");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("team_members_team_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("team_members_user_id_fkey");
        });

        modelBuilder.Entity<TeamTask>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("team_tasks_pkey");

            entity.ToTable("team_tasks");

            entity.Property(e => e.TaskId)
                .ValueGeneratedNever()
                .HasColumnName("task_id");
            entity.Property(e => e.AssignedTo).HasColumnName("assigned_to");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");

            entity.HasOne(d => d.AssignedToNavigation).WithMany(p => p.TeamTasks)
                .HasForeignKey(d => d.AssignedTo)
                .HasConstraintName("team_tasks_assigned_to_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamTasks)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("team_tasks_team_id_fkey");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.TopicId).HasName("topic_pkey");

            entity.ToTable("topic");

            entity.Property(e => e.TopicId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("topic_id");
            entity.Property(e => e.Category)
                .HasMaxLength(255)
                .HasColumnName("category");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.SubCategory)
                .HasMaxLength(255)
                .HasColumnName("sub_category");
            entity.Property(e => e.TopicName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("topic_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.TopicCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_topic_createdby_user");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.TopicUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_topic_updatedby_user");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "users_email_key").IsUnique();

            entity.Property(e => e.UserId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.DepartmentId).HasColumnName("department_id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasDefaultValueSql("''::text")
                .HasColumnName("password_hash");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.InverseCreatedByNavigation)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("users_created_by_fkey");

            entity.HasOne(d => d.Department).WithMany(p => p.Users)
                .HasForeignKey(d => d.DepartmentId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_users_department");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.InverseUpdatedByNavigation)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("users_updated_by_fkey");
        });

        modelBuilder.Entity<UserAssessmentProgress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_assessment_progress_pkey");

            entity.ToTable("user_assessment_progress");

            entity.HasIndex(e => new { e.UserId, e.AssessmentId }, "user_assessment_progress_user_id_assessment_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssessmentId).HasColumnName("assessment_id");
            entity.Property(e => e.Attempts)
                .HasDefaultValue(0)
                .HasColumnName("attempts");
            entity.Property(e => e.CompletedOn).HasColumnName("completed_on");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Passed).HasColumnName("passed");
            entity.Property(e => e.Score)
                .HasPrecision(5, 2)
                .HasColumnName("score");
            entity.Property(e => e.StartedOn).HasColumnName("started_on");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasDefaultValueSql("'NotStarted'::character varying")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<UserAssessmentResult>(entity =>
        {
            entity.HasKey(e => e.ResultId);

            entity.ToTable("UserAssessmentResult");

            entity.HasIndex(e => e.AssessmentId, "IX_UserAssessmentResult_AssessmentId");

            entity.HasIndex(e => e.UserId, "IX_UserAssessmentResult_UserId");

            entity.HasIndex(e => new { e.UserId, e.AssessmentId }, "IX_UserAssessmentResult_User_Assessment");

            entity.Property(e => e.ResultId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.AttemptedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.IsCompleted).HasDefaultValue(false);
            entity.Property(e => e.Passed).HasDefaultValue(false);
            entity.Property(e => e.UpdatedOn).HasColumnType("timestamp without time zone");
            entity.Property(e => e.UserAnswers)
                .IsRequired()
                .HasDefaultValueSql("'[]'::text");

            entity.HasOne(d => d.Assessment).WithMany(p => p.UserAssessmentResults)
                .HasForeignKey(d => d.AssessmentId)
                .HasConstraintName("FK_UserAssessmentResult_Assessment");

            entity.HasOne(d => d.User).WithMany(p => p.UserAssessmentResults)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserAssessmentResult_User");
        });

        modelBuilder.Entity<UserLearningPlan>(entity =>
        {
            entity.HasKey(e => e.UserLearningPlanId).HasName("UserLearningPlans_pkey");

            entity.Property(e => e.UserLearningPlanId).ValueGeneratedNever();
            entity.Property(e => e.AssignedOn).HasColumnType("timestamp without time zone");
            entity.Property(e => e.CompletedOn).HasColumnType("timestamp without time zone");
            entity.Property(e => e.ProgressPercent).HasPrecision(5, 2);
            entity.Property(e => e.StartedOn).HasColumnType("timestamp without time zone");
            entity.Property(e => e.Status).HasMaxLength(50);
        });

        modelBuilder.Entity<UserLessonProgress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_lesson_progress_pkey");

            entity.ToTable("user_lesson_progress");

            entity.HasIndex(e => new { e.UserId, e.LessonId }, "user_lesson_progress_user_id_lesson_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CompletedOn).HasColumnName("completed_on");
            entity.Property(e => e.LastAccessed).HasColumnName("last_accessed");
            entity.Property(e => e.LessonId).HasColumnName("lesson_id");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.StartedOn).HasColumnName("started_on");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasDefaultValueSql("'NotStarted'::character varying")
                .HasColumnName("status");
            entity.Property(e => e.TimeSpentSeconds)
                .HasDefaultValue(0)
                .HasColumnName("time_spent_seconds");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<UserModuleProgress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_module_progress_pkey");

            entity.ToTable("user_module_progress");

            entity.HasIndex(e => new { e.UserId, e.ModuleId }, "user_module_progress_user_id_module_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CompletedOn).HasColumnName("completed_on");
            entity.Property(e => e.LastAccessed).HasColumnName("last_accessed");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.StartedOn).HasColumnName("started_on");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasDefaultValueSql("'NotStarted'::character varying")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<UserPlanEnrollment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_plan_enrollment_pkey");

            entity.ToTable("user_plan_enrollment");

            entity.HasIndex(e => new { e.UserId, e.PlanId }, "user_plan_enrollment_user_id_plan_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssignedBy).HasColumnName("assigned_by");
            entity.Property(e => e.AssignedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("assigned_on");
            entity.Property(e => e.AssignmentType)
                .HasMaxLength(30)
                .HasDefaultValueSql("'Manager'::character varying")
                .HasColumnName("assignment_type");
            entity.Property(e => e.CompletedOn).HasColumnName("completed_on");
            entity.Property(e => e.PlanId).HasColumnName("plan_id");
            entity.Property(e => e.StartedOn).HasColumnName("started_on");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasDefaultValueSql("'Assigned'::character varying")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("user_roles_pkey");

            entity.ToTable("user_roles");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "user_roles_user_id_role_id_key").IsUnique();

            entity.Property(e => e.UserRoleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_role_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.UserRoleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_roles_created_by_fkey");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("user_roles_role_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.UserRoleUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_roles_updated_by_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_roles_user_id_fkey");
        });

        modelBuilder.Entity<UserSkill>(entity =>
        {
            entity.HasKey(e => e.UserSkillId).HasName("user_skills_pkey");

            entity.ToTable("user_skills");

            entity.Property(e => e.UserSkillId)
                .ValueGeneratedNever()
                .HasColumnName("user_skill_id");
            entity.Property(e => e.Proficiency).HasColumnName("proficiency");
            entity.Property(e => e.SkillId).HasColumnName("skill_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Skill).WithMany(p => p.UserSkills)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_skills_skill_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserSkills)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_skills_user_id_fkey");
        });

        modelBuilder.Entity<Week>(entity =>
        {
            entity.HasKey(e => e.WeekId).HasName("weeks_pkey");

            entity.ToTable("weeks");

            entity.HasIndex(e => e.PlanId, "idx_week_plan");

            entity.HasIndex(e => e.IsAiGenerated, "idx_weeks_is_ai_generated");

            entity.HasIndex(e => e.PlanId, "idx_weeks_plan_id");

            entity.Property(e => e.WeekId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("week_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsAiGenerated)
                .HasDefaultValue(false)
                .HasColumnName("is_ai_generated");
            entity.Property(e => e.LearningObjectives).HasColumnName("learning_objectives");
            entity.Property(e => e.Metadata).HasColumnType("jsonb");
            entity.Property(e => e.PlanId).HasColumnName("plan_id");
            entity.Property(e => e.Prerequisites).HasColumnName("prerequisites");
            entity.Property(e => e.UpdatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_on");
            entity.Property(e => e.WeekNumber).HasColumnName("week_number");

            entity.HasOne(d => d.Plan).WithMany(p => p.Weeks)
                .HasForeignKey(d => d.PlanId)
                .HasConstraintName("weeks_plan_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}