// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class Attachment
{
    public Guid AttachmentId { get; set; }

    public Guid? ItemId { get; set; }

    public Guid? VersionId { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public string FilePath { get; set; }

    public string Message { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public byte[] FileData { get; set; }

    public string MimeType { get; set; }

    public long? FileSize { get; set; }

    public List<float> Embedding { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual KnowledgeItem Item { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual KnowledgeVersion Version { get; set; }
}