// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class Presentation
{
    public Guid PresentationId { get; set; }

    public Guid? TeamId { get; set; }

    public Guid? EventId { get; set; }

    public DateTime? PresentationDate { get; set; }

    public int? Score { get; set; }

    public int? Rank { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Event Event { get; set; }

    public virtual Team Team { get; set; }
}