// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class ActivityLog
{
    public Guid ActivityId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? ItemId { get; set; }

    public Guid? EventId { get; set; }

    public string Details { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string Action { get; set; }

    public virtual Event Event { get; set; }

    public virtual KnowledgeItem Item { get; set; }

    public virtual User User { get; set; }
}