// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class Category
{
    public Guid CategoryId { get; set; }

    public string CategoryName { get; set; }

    public Guid? DomainId { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Domain Domain { get; set; }

    public virtual ICollection<KnowledgeItem> KnowledgeItems { get; set; } = new List<KnowledgeItem>();

    public virtual User UpdatedByNavigation { get; set; }
}