// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class Event
{
    public Guid EventId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public Guid? OwnerId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public string EventType { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<EventKnowledgeItem> EventKnowledgeItems { get; set; } = new List<EventKnowledgeItem>();

    public virtual ICollection<Mentor> Mentors { get; set; } = new List<Mentor>();

    public virtual User Owner { get; set; }

    public virtual ICollection<Presentation> Presentations { get; set; } = new List<Presentation>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();

    public virtual User UpdatedByNavigation { get; set; }
}