// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class KnowledgeTag
{
    public Guid TagId { get; set; }

    public Guid? ItemId { get; set; }

    public string TagName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public Guid? VersionId { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual KnowledgeItem Item { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual KnowledgeVersion Version { get; set; }
}