// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class KnowledgeReviewerAssignment
{
    public Guid AssignmentId { get; set; }

    public Guid? ItemId { get; set; }

    public Guid? ReviewerId { get; set; }

    public Guid? AssignedBy { get; set; }

    public DateTime? AssignedOn { get; set; }

    public virtual User AssignedByNavigation { get; set; }

    public virtual KnowledgeItem Item { get; set; }

    public virtual ICollection<KnowledgeReview> KnowledgeReviews { get; set; } = new List<KnowledgeReview>();

    public virtual User Reviewer { get; set; }
}