// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class KnowledgeItem
{
    public Guid ItemId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Guid? DomainId { get; set; }

    public string KnowledgeItem1 { get; set; }

    public Guid? CategoryId { get; set; }

    public Guid? OwnerId { get; set; }

    public string Status { get; set; }

    public int? Version { get; set; }

    public string Visibility { get; set; }

    public bool? IsEventItem { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public string Framework { get; set; }

    public string Language { get; set; }

    public string Metadata { get; set; }

    public string KnowledgeItem1 { get; set; }

    public List<float> Embedding { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual Category Category { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Domain Domain { get; set; }

    public virtual ICollection<Engagement> Engagements { get; set; } = new List<Engagement>();

    public virtual ICollection<EventKnowledgeItem> EventKnowledgeItems { get; set; } = new List<EventKnowledgeItem>();

    public virtual ICollection<KnowledgeReviewerAssignment> KnowledgeReviewerAssignments { get; set; } = new List<KnowledgeReviewerAssignment>();

    public virtual ICollection<KnowledgeReview> KnowledgeReviews { get; set; } = new List<KnowledgeReview>();

    public virtual ICollection<KnowledgeTag> KnowledgeTags { get; set; } = new List<KnowledgeTag>();

    public virtual ICollection<KnowledgeVersion> KnowledgeVersions { get; set; } = new List<KnowledgeVersion>();

    public virtual User Owner { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}