// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class KnowledgeVersion
{
    public Guid VersionId { get; set; }

    public Guid ItemId { get; set; }

    public int VersionNumber { get; set; }

    public string ChangesSummary { get; set; }

    public string FilePath { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual KnowledgeItem Item { get; set; }

    public virtual ICollection<KnowledgeTag> KnowledgeTags { get; set; } = new List<KnowledgeTag>();
}