// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using KnowLedger_Synaptix.Enums;

namespace KnowLedger_Synaptix.Models;

public partial class Role
{
    public Guid RoleId { get; set; }

<<<<<<< HEAD
    public string RoleName { get; set; }

=======
    public RoleName RoleName { get; set; }
>>>>>>> d254d38a840fa3205332ee1ad654f1c0b600c1bf
    public string Description { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}