// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class SpotlightItem
{
    public Guid SpotlightId { get; set; }

    public string Type { get; set; }

    public string ContentText { get; set; }

    public string ResourceLink { get; set; }

    public DateOnly? ValidDate { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}