// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KnowLedger_Synaptix.Models;

public partial class UserBadge
{
    public Guid UserBadgeId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? BadgeId { get; set; }

    public DateTime? AwardedOn { get; set; }

    public Guid? AwardedBy { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public virtual User AwardedByNavigation { get; set; }

    public virtual Badge Badge { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual User User { get; set; }
}