// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Leaderboard
{
    public Guid LeaderboardId { get; set; }

    public Guid? UserId { get; set; }

    public int? Points { get; set; }

    public int? Rank { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual User User { get; set; }
}