// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Domain.Entities;

public partial class Module
{
    public Guid ModuleId { get; set; }

    public Guid TopicId { get; set; }

    public string ModuleName { get; set; }

    public string Description { get; set; }

    public string ContentLink { get; set; }

    public int? OrderNo { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Topic Topic { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual ICollection<UserModuleProgress> UserModuleProgresses { get; set; } = new List<UserModuleProgress>();
}