// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Knowledge_Repository.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Xml.Linq;

namespace Knowledge_Repository.Domain.Entities;

public partial class Topic
{
    public Guid TopicId { get; set; }

    public string TopicName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Module> Modules { get; set; } = new List<Module>();

    public virtual User UpdatedByNavigation { get; set; }

    public virtual ICollection<UserModuleProgress> UserModuleProgresses { get; set; } = new List<UserModuleProgress>();
}