// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class Announcement
{
    public Guid AnnouncementId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}