// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class JuryCommunication
{
    public Guid CommunicationId { get; set; }

    public Guid EventId { get; set; }

    public Guid TeamId { get; set; }

    public Guid JuryId { get; set; }

    public int? Score { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual Event Event { get; set; }

    public virtual User Jury { get; set; }

    public virtual ICollection<JuryReply> JuryReplies { get; set; } = new List<JuryReply>();

    public virtual Team Team { get; set; }
}