// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class JuryReply
{
    public Guid ReplyId { get; set; }

    public Guid CommunicationId { get; set; }

    public Guid UserId { get; set; }

    public string ReplyMessage { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual JuryCommunication Communication { get; set; }

    public virtual User User { get; set; }
}