// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Knowledge_Repository.Api.Models;

public partial class Knowledge_RepositoryContext : DbContext
{
    public Knowledge_RepositoryContext(DbContextOptions<Knowledge_RepositoryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<Announcement> Announcements { get; set; }

    public virtual DbSet<Attachment> Attachments { get; set; }

    public virtual DbSet<Badge> Badges { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Domain> Domains { get; set; }

    public virtual DbSet<Engagement> Engagements { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<EventJury> EventJuries { get; set; }

    public virtual DbSet<EventKnowledgeItem> EventKnowledgeItems { get; set; }

    public virtual DbSet<KnowledgeItem> KnowledgeItems { get; set; }

    public virtual DbSet<KnowledgeReview> KnowledgeReviews { get; set; }

    public virtual DbSet<KnowledgeReviewerAssignment> KnowledgeReviewerAssignments { get; set; }

    public virtual DbSet<KnowledgeTag> KnowledgeTags { get; set; }

    public virtual DbSet<KnowledgeVersion> KnowledgeVersions { get; set; }

    public virtual DbSet<Leaderboard> Leaderboards { get; set; }

    public virtual DbSet<Mentor> Mentors { get; set; }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<Presentation> Presentations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SpotlightItem> SpotlightItems { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamMember> TeamMembers { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserBadge> UserBadges { get; set; }

    public virtual DbSet<UserModuleProgress> UserModuleProgresses { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("activity_action_enum", new[] { "Upload", "Approve", "Reject", "Comment", "Like", "Event Created" })
            .HasPostgresEnum("announcement_priority_enum", new[] { "Urgent", "Reminder", "Info" })
            .HasPostgresEnum("engagement_action_enum", new[] { "View", "Like", "Comment", "Share" })
            .HasPostgresEnum("event_type_enum", new[] { "Ideathon", "Hackathon", "Coding Challenge", "Knowledge Quest" })
            .HasPostgresEnum("file_type_enum", new[] { "File", "Text", "Video", "Audio" })
            .HasPostgresEnum("knowledge_status_enum", new[] { "Draft", "Submitted", "Under Review", "Approved", "Rejected", "Archived" })
            .HasPostgresEnum("leaderboard_category_enum", new[] { "Overall", "Domain Experts", "Rising Stars", "Event Champions" })
            .HasPostgresEnum("leaderboard_period_enum", new[] { "Daily", "Weekly", "Monthly" })
            .HasPostgresEnum("participant_status_enum", new[] { "Registered", "Checked-in", "Cancelled" })
            .HasPostgresEnum("presentation_type_enum", new[] { "Live", "Recorded" })
            .HasPostgresEnum("review_status_enum", new[] { "Reviewed", "Approved", "Rejected", "Revision Requested" })
            .HasPostgresEnum("reviewer_assignment_status_enum", new[] { "Pending", "Cancelled", "Reassigned" })
            .HasPostgresEnum("role_name_enum", new[] { "Contributor", "Reviewer", "Approver", "Admin", "Reader" })
            .HasPostgresEnum("spotlight_type_enum", new[] { "quote", "text" })
            .HasPostgresEnum("submission_status_enum", new[] { "Submitted", "Reviewed", "Selected", "Winner" })
            .HasPostgresEnum("team_member_role_enum", new[] { "Leader", "Member" })
            .HasPostgresEnum("visibility_enum", new[] { "Public", "Department-Restricted", "Private" })
            .HasPostgresExtension("pgcrypto")
            .HasPostgresExtension("vector");

        modelBuilder.Entity<ActivityLog>(entity =>
        {
            entity.HasKey(e => e.ActivityId).HasName("activity_log_pkey");

            entity.ToTable("activity_log");

            entity.Property(e => e.ActivityId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("activity_id");
            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Details).HasColumnName("details");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Event).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("activity_log_event_id_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("activity_log_item_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("activity_log_user_id_fkey");
        });

        modelBuilder.Entity<Announcement>(entity =>
        {
            entity.HasKey(e => e.AnnouncementId).HasName("announcements_pkey");

            entity.ToTable("announcements");

            entity.Property(e => e.AnnouncementId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("announcement_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Announcements)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("announcements_created_by_fkey");
        });

        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.HasKey(e => e.AttachmentId).HasName("attachments_pkey");

            entity.ToTable("attachments");

            entity.Property(e => e.AttachmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("attachment_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.FileData).HasColumnName("file_data");
            entity.Property(e => e.FileName).HasColumnName("file_name");
            entity.Property(e => e.FilePath).HasColumnName("file_path");
            entity.Property(e => e.FileSize).HasColumnName("file_size");
            entity.Property(e => e.FileType).HasColumnName("file_type");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.MimeType).HasColumnName("mime_type");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.VersionId).HasColumnName("version_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.AttachmentCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("attachments_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("attachments_item_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.AttachmentUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("attachments_updated_by_fkey");

            entity.HasOne(d => d.Version).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("attachments_version_id_fkey");
        });

        modelBuilder.Entity<Badge>(entity =>
        {
            entity.HasKey(e => e.BadgeId).HasName("badges_pkey");

            entity.ToTable("badges");

            entity.HasIndex(e => e.BadgeName, "badges_badge_name_key").IsUnique();

            entity.Property(e => e.BadgeId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("badge_id");
            entity.Property(e => e.BadgeName)
                .IsRequired()
                .HasColumnName("badge_name");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IconUrl).HasColumnName("icon_url");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.BadgeCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("badges_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.BadgeUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("badges_updated_by_fkey");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("categories_pkey");

            entity.ToTable("categories");

            entity.HasIndex(e => new { e.CategoryName, e.DomainId }, "categories_category_name_domain_id_key").IsUnique();

            entity.Property(e => e.CategoryId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("category_id");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasColumnName("category_name");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DomainId).HasColumnName("domain_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CategoryCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("categories_created_by_fkey");

            entity.HasOne(d => d.Domain).WithMany(p => p.Categories)
                .HasForeignKey(d => d.DomainId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("categories_domain_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.CategoryUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("categories_updated_by_fkey");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentId).HasName("departments_pkey");

            entity.ToTable("departments");

            entity.HasIndex(e => e.DepartmentName, "departments_department_name_key").IsUnique();

            entity.Property(e => e.DepartmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("department_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.DepartmentName)
                .IsRequired()
                .HasColumnName("department_name");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.HeadId).HasColumnName("head_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DepartmentCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("departments_created_by_fkey");

            entity.HasOne(d => d.Head).WithMany(p => p.DepartmentHeads)
                .HasForeignKey(d => d.HeadId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("departments_head_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.DepartmentUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("departments_updated_by_fkey");
        });

        modelBuilder.Entity<Domain>(entity =>
        {
            entity.HasKey(e => e.DomainId).HasName("domains_pkey");

            entity.ToTable("domains");

            entity.HasIndex(e => e.DomainName, "domains_domain_name_key").IsUnique();

            entity.Property(e => e.DomainId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("domain_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DomainName)
                .IsRequired()
                .HasColumnName("domain_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DomainCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("domains_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.DomainUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("domains_updated_by_fkey");
        });

        modelBuilder.Entity<Engagement>(entity =>
        {
            entity.HasKey(e => e.EngagementId).HasName("engagements_pkey");

            entity.ToTable("engagements");

            entity.Property(e => e.EngagementId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("engagement_id");
            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.CommentText).HasColumnName("comment_text");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EngagementType).HasMaxLength(50);
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.ParentCommentId).HasColumnName("parent_comment_id");
            entity.Property(e => e.Points)
                .HasDefaultValue(0)
                .HasColumnName("points");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EngagementCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("engagements_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.Engagements)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("engagements_item_id_fkey");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_engagement_parent_comment");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.EngagementUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("engagements_updated_by_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.EngagementUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("engagements_user_id_fkey");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("events_pkey");

            entity.ToTable("events");

            entity.Property(e => e.EventId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("event_id");
            entity.Property(e => e.ContactEmail).HasColumnName("contact_email");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasColumnName("event_type");
            entity.Property(e => e.FinalSubmissionDeadline).HasColumnName("final_submission_deadline");
            entity.Property(e => e.IdeaPresentationEnd).HasColumnName("idea_presentation_end");
            entity.Property(e => e.IdeaPresentationStart).HasColumnName("idea_presentation_start");
            entity.Property(e => e.MentorCheckpointEnd).HasColumnName("mentor_checkpoint_end");
            entity.Property(e => e.MentorCheckpointStart).HasColumnName("mentor_checkpoint_start");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.RegistrationCloseDate).HasColumnName("registration_close_date");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.WinnersAnnouncementDate).HasColumnName("winners_announcement_date");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EventCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("events_created_by_fkey");

            entity.HasOne(d => d.Owner).WithMany(p => p.EventOwners)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("events_owner_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.EventUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("events_updated_by_fkey");
        });

        modelBuilder.Entity<EventJury>(entity =>
        {
            entity.HasKey(e => e.EventJuryId).HasName("event_jury_pkey");

            entity.ToTable("event_jury");

            entity.Property(e => e.EventJuryId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("event_jury_id");
            entity.Property(e => e.AssignedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("assigned_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Event).WithMany(p => p.EventJuries)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("fk_event_jury_event");

            entity.HasOne(d => d.User).WithMany(p => p.EventJuries)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_event_jury_user");
        });

        modelBuilder.Entity<EventKnowledgeItem>(entity =>
        {
            entity.HasKey(e => e.EventItemId).HasName("event_knowledge_items_pkey");

            entity.ToTable("event_knowledge_items");

            entity.Property(e => e.EventItemId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("event_item_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EventKnowledgeItemCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("event_knowledge_items_created_by_fkey");

            entity.HasOne(d => d.Event).WithMany(p => p.EventKnowledgeItems)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("event_knowledge_items_event_id_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.EventKnowledgeItems)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("event_knowledge_items_item_id_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.EventKnowledgeItems)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("event_knowledge_items_team_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.EventKnowledgeItemUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("event_knowledge_items_updated_by_fkey");
        });

        modelBuilder.Entity<KnowledgeItem>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("knowledge_items_pkey");

            entity.ToTable("knowledge_items");

            entity.Property(e => e.ItemId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("item_id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DomainId).HasColumnName("domain_id");
            entity.Property(e => e.Framework)
                .HasColumnType("jsonb")
                .HasColumnName("framework");
            entity.Property(e => e.IsEventItem)
                .HasDefaultValue(false)
                .HasColumnName("is_event_item");
            entity.Property(e => e.KnowledgeItem1).HasColumnName("knowledge_item");
            entity.Property(e => e.Language)
                .HasColumnType("jsonb")
                .HasColumnName("language");
            entity.Property(e => e.Metadata)
                .HasColumnType("jsonb")
                .HasColumnName("metadata");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'Draft'::knowledge_status_enum")
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.Version)
                .HasDefaultValue(1)
                .HasColumnName("version");
            entity.Property(e => e.Visibility)
                .HasDefaultValueSql("'Public'::visibility_enum")
                .HasColumnName("visibility");

            entity.HasOne(d => d.Category).WithMany(p => p.KnowledgeItems)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_category_id_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.KnowledgeItemCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_created_by_fkey");

            entity.HasOne(d => d.Domain).WithMany(p => p.KnowledgeItems)
                .HasForeignKey(d => d.DomainId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_domain_id_fkey");

            entity.HasOne(d => d.Owner).WithMany(p => p.KnowledgeItemOwners)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_owner_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.KnowledgeItemUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_items_updated_by_fkey");
        });

        modelBuilder.Entity<KnowledgeReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("knowledge_reviews_pkey");

            entity.ToTable("knowledge_reviews");

            entity.Property(e => e.ReviewId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("review_id");
            entity.Property(e => e.AssignmentId).HasColumnName("assignment_id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.ReviewedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("reviewed_on");
            entity.Property(e => e.ReviewerId).HasColumnName("reviewer_id");

            entity.HasOne(d => d.Assignment).WithMany(p => p.KnowledgeReviews)
                .HasForeignKey(d => d.AssignmentId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_reviews_assignment_id_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeReviews)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_reviews_item_id_fkey");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.KnowledgeReviews)
                .HasForeignKey(d => d.ReviewerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_reviews_reviewer_id_fkey");
        });

        modelBuilder.Entity<KnowledgeReviewerAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("knowledge_reviewer_assignments_pkey");

            entity.ToTable("knowledge_reviewer_assignments");

            entity.Property(e => e.AssignmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("assignment_id");
            entity.Property(e => e.AssignedBy).HasColumnName("assigned_by");
            entity.Property(e => e.AssignedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("assigned_on");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.ReviewerId).HasColumnName("reviewer_id");

            entity.HasOne(d => d.AssignedByNavigation).WithMany(p => p.KnowledgeReviewerAssignmentAssignedByNavigations)
                .HasForeignKey(d => d.AssignedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_reviewer_assignments_assigned_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeReviewerAssignments)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_reviewer_assignments_item_id_fkey");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.KnowledgeReviewerAssignmentReviewers)
                .HasForeignKey(d => d.ReviewerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_reviewer_assignments_reviewer_id_fkey");
        });

        modelBuilder.Entity<KnowledgeTag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("knowledge_tags_pkey");

            entity.ToTable("knowledge_tags");

            entity.HasIndex(e => new { e.ItemId, e.TagName, e.VersionId }, "knowledge_tags_item_id_tag_name_version_id_key").IsUnique();

            entity.Property(e => e.TagId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("tag_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasColumnName("tag_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.VersionId).HasColumnName("version_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.KnowledgeTagCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_tags_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeTags)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("knowledge_tags_item_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.KnowledgeTagUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_tags_updated_by_fkey");

            entity.HasOne(d => d.Version).WithMany(p => p.KnowledgeTags)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_tags_version_id_fkey");
        });

        modelBuilder.Entity<KnowledgeVersion>(entity =>
        {
            entity.HasKey(e => e.VersionId).HasName("knowledge_versions_pkey");

            entity.ToTable("knowledge_versions");

            entity.HasIndex(e => new { e.ItemId, e.VersionNumber }, "knowledge_versions_item_id_version_number_key").IsUnique();

            entity.Property(e => e.VersionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("version_id");
            entity.Property(e => e.ChangesSummary).HasColumnName("changes_summary");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.FilePath).HasColumnName("file_path");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.VersionNumber).HasColumnName("version_number");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.KnowledgeVersions)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("knowledge_versions_created_by_fkey");

            entity.HasOne(d => d.Item).WithMany(p => p.KnowledgeVersions)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("knowledge_versions_item_id_fkey");
        });

        modelBuilder.Entity<Leaderboard>(entity =>
        {
            entity.HasKey(e => e.LeaderboardId).HasName("leaderboards_pkey");

            entity.ToTable("leaderboards");

            entity.Property(e => e.LeaderboardId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("leaderboard_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Points)
                .HasDefaultValue(0)
                .HasColumnName("points");
            entity.Property(e => e.Rank).HasColumnName("rank");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Leaderboards)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("leaderboards_user_id_fkey");
        });

        modelBuilder.Entity<Mentor>(entity =>
        {
            entity.HasKey(e => e.MentorId).HasName("mentors_pkey");

            entity.ToTable("mentors");

            entity.Property(e => e.MentorId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("mentor_id");
            entity.Property(e => e.AssignedTeamId).HasColumnName("assigned_team_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.AssignedTeam).WithMany(p => p.Mentors)
                .HasForeignKey(d => d.AssignedTeamId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("mentors_assigned_team_id_fkey");

            entity.HasOne(d => d.Event).WithMany(p => p.Mentors)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("mentors_event_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.Mentors)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("mentors_user_id_fkey");
        });

        modelBuilder.Entity<Module>(entity =>
        {
            entity.HasKey(e => e.ModuleId).HasName("modules_pkey");

            entity.ToTable("modules");

            entity.Property(e => e.ModuleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("module_id");
            entity.Property(e => e.ContentLink).HasColumnName("content_link");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ModuleName)
                .IsRequired()
                .HasColumnName("module_name");
            entity.Property(e => e.OrderNo).HasColumnName("order_no");
            entity.Property(e => e.TopicId).HasColumnName("topic_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ModuleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("modules_created_by_fkey");

            entity.HasOne(d => d.Topic).WithMany(p => p.Modules)
                .HasForeignKey(d => d.TopicId)
                .HasConstraintName("modules_topic_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.ModuleUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("modules_updated_by_fkey");
        });

        modelBuilder.Entity<Presentation>(entity =>
        {
            entity.HasKey(e => e.PresentationId).HasName("presentations_pkey");

            entity.ToTable("presentations");

            entity.Property(e => e.PresentationId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("presentation_id");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.PresentationDate).HasColumnName("presentation_date");
            entity.Property(e => e.Rank).HasColumnName("rank");
            entity.Property(e => e.Score).HasColumnName("score");
            entity.Property(e => e.TeamId).HasColumnName("team_id");

            entity.HasOne(d => d.Event).WithMany(p => p.Presentations)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("presentations_event_id_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.Presentations)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("presentations_team_id_fkey");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("roles_pkey");

            entity.ToTable("roles");

            entity.HasIndex(e => e.RoleName, "roles_role_name_key").IsUnique();

            entity.Property(e => e.RoleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("role_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasColumnName("role_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.RoleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("roles_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.RoleUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("roles_updated_by_fkey");
        });

        modelBuilder.Entity<SpotlightItem>(entity =>
        {
            entity.HasKey(e => e.SpotlightId).HasName("spotlight_items_pkey");

            entity.ToTable("spotlight_items");

            entity.Property(e => e.SpotlightId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("spotlight_id");
            entity.Property(e => e.ContentText).HasColumnName("content_text");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.ResourceLink).HasColumnName("resource_link");
            entity.Property(e => e.Type).HasColumnName("type");
            entity.Property(e => e.ValidDate).HasColumnName("valid_date");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.SpotlightItems)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("spotlight_items_created_by_fkey");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("teams_pkey");

            entity.ToTable("teams");

            entity.Property(e => e.TeamId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("team_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasColumnName("team_name");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Teams)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("teams_created_by_fkey");

            entity.HasOne(d => d.Event).WithMany(p => p.Teams)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("teams_event_id_fkey");
        });

        modelBuilder.Entity<TeamMember>(entity =>
        {
            entity.HasKey(e => e.TeamMemberId).HasName("team_members_pkey");

            entity.ToTable("team_members");

            entity.HasIndex(e => new { e.TeamId, e.UserId }, "team_members_team_id_user_id_key").IsUnique();

            entity.Property(e => e.TeamMemberId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("team_member_id");
            entity.Property(e => e.JoinedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("joined_on");
            entity.Property(e => e.Role)
                .IsRequired()
                .HasDefaultValueSql("'Member'::text")
                .HasColumnName("role");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("team_members_team_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("team_members_user_id_fkey");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.TopicId).HasName("topics_pkey");

            entity.ToTable("topics");

            entity.HasIndex(e => e.TopicName, "topics_name_key").IsUnique();

            entity.Property(e => e.TopicId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("topic_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.TopicName)
                .IsRequired()
                .HasColumnName("topic_name");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.TopicCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("topics_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.TopicUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("topics_updated_by_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "users_email_key").IsUnique();

            entity.Property(e => e.UserId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.DepartmentId).HasColumnName("department_id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasDefaultValueSql("''::text")
                .HasColumnName("password_hash");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.InverseCreatedByNavigation)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("users_created_by_fkey");

            entity.HasOne(d => d.Department).WithMany(p => p.Users)
                .HasForeignKey(d => d.DepartmentId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_users_department");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.InverseUpdatedByNavigation)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("users_updated_by_fkey");
        });

        modelBuilder.Entity<UserBadge>(entity =>
        {
            entity.HasKey(e => e.UserBadgeId).HasName("user_badges_pkey");

            entity.ToTable("user_badges");

            entity.HasIndex(e => new { e.UserId, e.BadgeId }, "user_badges_user_id_badge_id_key").IsUnique();

            entity.Property(e => e.UserBadgeId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_badge_id");
            entity.Property(e => e.AwardedBy).HasColumnName("awarded_by");
            entity.Property(e => e.AwardedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("awarded_on");
            entity.Property(e => e.BadgeId).HasColumnName("badge_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.AwardedByNavigation).WithMany(p => p.UserBadgeAwardedByNavigations)
                .HasForeignKey(d => d.AwardedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_badges_awarded_by_fkey");

            entity.HasOne(d => d.Badge).WithMany(p => p.UserBadges)
                .HasForeignKey(d => d.BadgeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("user_badges_badge_id_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.UserBadgeCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_badges_created_by_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.UserBadgeUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_badges_updated_by_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserBadgeUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("user_badges_user_id_fkey");
        });

        modelBuilder.Entity<UserModuleProgress>(entity =>
        {
            entity.HasKey(e => e.ProgressId).HasName("user_module_progress_pkey");

            entity.ToTable("user_module_progress");

            entity.Property(e => e.ProgressId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("progress_id");
            entity.Property(e => e.CompletedOn).HasColumnName("completed_on");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("created_at");
            entity.Property(e => e.LastAccessed)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("last_accessed");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.StartedOn)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("started_on");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'Not Started'::text")
                .HasColumnName("status");
            entity.Property(e => e.TestAttemptedOn).HasColumnName("test_attempted_on");
            entity.Property(e => e.TestStatus)
                .HasDefaultValueSql("'Not Started'::text")
                .HasColumnName("test_status");
            entity.Property(e => e.TopicId).HasColumnName("topic_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Module).WithMany(p => p.UserModuleProgresses)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("user_module_progress_module_id_fkey");

            entity.HasOne(d => d.Topic).WithMany(p => p.UserModuleProgresses)
                .HasForeignKey(d => d.TopicId)
                .HasConstraintName("user_module_progress_topic_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserModuleProgresses)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_module_progress_user_id_fkey");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("user_roles_pkey");

            entity.ToTable("user_roles");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "user_roles_user_id_role_id_key").IsUnique();

            entity.Property(e => e.UserRoleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_role_id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_on");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");
            entity.Property(e => e.UpdatedOn).HasColumnName("updated_on");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.UserRoleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_roles_created_by_fkey");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("user_roles_role_id_fkey");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.UserRoleUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("user_roles_updated_by_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_roles_user_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}