// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class Mentor
{
    public Guid MentorId { get; set; }

    public Guid? EventId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? AssignedTeamId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Team AssignedTeam { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}