// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class PasswordReset
{
    public Guid PasswordResetId { get; set; }

    public Guid UserId { get; set; }

    public string CodeHash { get; set; }

    public DateTime CodeExpiresAt { get; set; }

    public bool CodeUsed { get; set; }

    public string ResetTokenHash { get; set; }

    public DateTime? ResetTokenExpiresAt { get; set; }

    public bool ResetTokenUsed { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual User User { get; set; }
}