// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class TeamFeedback
{
    public Guid FeedbackId { get; set; }

    public Guid MentorId { get; set; }

    public Guid TeamId { get; set; }

    public Guid EventId { get; set; }

    public string FeedbackText { get; set; }

    public int? ProgressRating { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public DateTime? LastReplyOn { get; set; }

    public virtual Event Event { get; set; }

    public virtual Mentor Mentor { get; set; }

    public virtual Team Team { get; set; }

    public virtual ICollection<TeamFeedbackReply> TeamFeedbackReplies { get; set; } = new List<TeamFeedbackReply>();
}