// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Knowledge_Repository.Api.Models;

public partial class Team
{
    public Guid TeamId { get; set; }

    public Guid? EventId { get; set; }

    public string TeamName { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<EventKnowledgeItem> EventKnowledgeItems { get; set; } = new List<EventKnowledgeItem>();

    public virtual ICollection<Mentor> Mentors { get; set; } = new List<Mentor>();

    public virtual ICollection<Presentation> Presentations { get; set; } = new List<Presentation>();

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();
}